#include "guardian.h"
#include <arpa/inet.h>
#include <netinet/in.h>
#include <pthread.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>
#include <ctype.h>

static guardian_config G; static SSL_CTX *TLS;
static void reply(SSL*c,const char*s,const char*t,const char*b,const char*x){char h[2048];int n=(int)strlen(b);snprintf(h,sizeof(h),"HTTP/1.1 %s\r\nContent-Type: %s\r\nContent-Length: %d\r\nCache-Control: no-store\r\n%sConnection: close\r\n\r\n",s,t,n,x?x:"");SSL_write(c,h,(int)strlen(h));SSL_write(c,b,n);}
static int auth(const char*r){return strstr(r,"Cookie: pg_session=1")!=NULL;}
static int hex(char c){if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;return -1;}
static void urldecode(char*out,size_t n,const char*in){size_t j=0;for(size_t i=0;in[i]&&j+1<n;i++){if(in[i]=='%'&&in[i+1]&&in[i+2]){int a=hex(in[i+1]),b=hex(in[i+2]);if(a>=0&&b>=0){out[j++]=(char)((a<<4)|b);i+=2;continue;}}out[j++]=(in[i]=='+'?' ':in[i]);}out[j]=0;}
static const char*mime(const char*p){const char*e=strrchr(p,'.');if(!e)return"application/octet-stream";if(!strcmp(e,".html"))return"text/html; charset=utf-8";if(!strcmp(e,".js"))return"application/javascript";if(!strcmp(e,".css"))return"text/css";if(!strcmp(e,".json"))return"application/json";if(!strcmp(e,".svg"))return"image/svg+xml";return"application/octet-stream";}
static void static_file(SSL*c,const char*p,const char*t){FILE*f=fopen(p,"rb");if(!f){reply(c,"404 Not Found","text/plain","Not found",0);return;}if(fseek(f,0,SEEK_END)!=0){fclose(f);reply(c,"500 Internal Server Error","text/plain","IO error",0);return;}long z=ftell(f);if(z<0||z>8*1024*1024){fclose(f);reply(c,"500 Internal Server Error","text/plain","Invalid file",0);return;}rewind(f);char*b=malloc((size_t)z+1);if(!b){fclose(f);reply(c,"500 Internal Server Error","text/plain","OOM",0);return;}size_t n=fread(b,1,(size_t)z,f);fclose(f);b[n]=0;reply(c,"200 OK",t?t:mime(p),b,0);free(b);}
static int endpoint_from_json(const char*b,char*out,size_t n){const char*k=strstr(b,"\"endpoint\"");if(!k)return-1;k=strchr(k,':');if(!k)return-1;k++;while(*k&&(*k==' '||*k=='\"'))k++;size_t j=0;while(*k&&*k!='\"'&&j+1<n){if(*k=='\\'&&k[1])k++;out[j++]=*k++;}out[j]=0;return j?0:-1;}
static void handle(SSL*c){char r[32768]={0};int n=SSL_read(c,r,sizeof(r)-1);if(n<=0)return;char method[8]={0},path[512]={0};if(sscanf(r,"%7s %511s",method,path)!=2){reply(c,"400 Bad Request","text/plain","Bad request",0);return;}
if(!strcmp(path,"/")||!strcmp(path,"/index.html")){static_file(c,"/opt/pi-guardian/web/index.html","text/html; charset=utf-8");return;}if(!strcmp(path,"/manifest.json")){static_file(c,"/opt/pi-guardian/web/manifest.json",0);return;}if(!strcmp(path,"/sw.js")){static_file(c,"/opt/pi-guardian/web/sw.js","application/javascript");return;}if(!strcmp(path,"/icon.svg")){static_file(c,"/opt/pi-guardian/web/icon.svg","image/svg+xml");return;}if(!strcmp(path,"/style.css")){static_file(c,"/opt/pi-guardian/web/style.css","text/css");return;}if(!strcmp(path,"/app.js")){static_file(c,"/opt/pi-guardian/web/app.js","application/javascript");return;}
if(!strcmp(path,"/api/login")&&!strcmp(method,"POST")){char*b=strstr(r,"\r\n\r\n");b=b?b+4:"";char ru[128]={0},rp[256]={0},u[64]={0},p[128]={0};if(sscanf(b,"username=%127[^&]&password=%255s",ru,rp)==2){urldecode(u,sizeof(u),ru);urldecode(p,sizeof(p),rp);}if(!strcmp(u,G.username)&&!strcmp(p,G.password))reply(c,"200 OK","application/json","{\"ok\":true}","Set-Cookie: pg_session=1; Path=/; HttpOnly; Secure; SameSite=Strict\r\n");else reply(c,"401 Unauthorized","application/json","{\"ok\":false}",0);return;}
if(!strcmp(path,"/api/logout")){reply(c,"200 OK","application/json","{\"ok\":true}","Set-Cookie: pg_session=; Max-Age=0; Path=/; HttpOnly; Secure; SameSite=Strict\r\n");return;}if(!auth(r)){reply(c,"401 Unauthorized","application/json","{\"error\":\"login required\"}",0);return;}
if(!strcmp(path,"/api/status")){char j[512];snprintf(j,sizeof(j),"{\"cpu\":%d,\"ram\":%d,\"disk\":%d,\"temp\":%d,\"port\":81,\"https\":true}",monitor_cpu(),monitor_ram(),monitor_disk(),monitor_temp());reply(c,"200 OK","application/json",j,0);return;}
if(!strcmp(path,"/api/push/vapid-public-key")){char key[128]={0};if(push_public_key(key,sizeof(key))<0)reply(c,"500 Internal Server Error","application/json","{\"error\":\"vapid unavailable\"}",0);else{char j[192];snprintf(j,sizeof(j),"{\"publicKey\":\"%s\"}",key);reply(c,"200 OK","application/json",j,0);}return;}
if(!strcmp(path,"/api/push/subscribe")&&!strcmp(method,"POST")){char*b=strstr(r,"\r\n\r\n");char ep[4096]={0};if(b&&endpoint_from_json(b+4,ep,sizeof(ep))==0&&push_subscribe(ep)==0)reply(c,"201 Created","application/json","{\"ok\":true}",0);else reply(c,"400 Bad Request","application/json","{\"ok\":false}",0);return;}
if(!strcmp(path,"/api/push/unsubscribe")&&!strcmp(method,"POST")){char*b=strstr(r,"\r\n\r\n");char ep[4096]={0};if(b&&endpoint_from_json(b+4,ep,sizeof(ep))==0&&push_unsubscribe(ep)==0)reply(c,"200 OK","application/json","{\"ok\":true}",0);else reply(c,"400 Bad Request","application/json","{\"ok\":false}",0);return;}
if(!strcmp(path,"/api/notifications/latest")){static_file(c,"/var/lib/pi-guardian/latest-event.json","application/json");return;}reply(c,"404 Not Found","application/json","{\"error\":\"not found\"}",0);}
static void*watch(void*x){(void)x;for(;;){int cpu=monitor_cpu(),ram=monitor_ram(),disk=monitor_disk(),temp=monitor_temp();if(cpu>95||ram>95||disk>90||temp>80){char m[160];snprintf(m,sizeof(m),"CPU %d%% RAM %d%% disk %d%% temperature %dC",cpu,ram,disk,temp);notify_event("CRITICAL","System pressure",m);}sleep(15);}return 0;}
static SSL_CTX*make_tls(void){SSL_CTX*c=SSL_CTX_new(TLS_server_method());if(!c)return NULL;SSL_CTX_set_min_proto_version(c,TLS1_2_VERSION);SSL_CTX_set_options(c,SSL_OP_NO_COMPRESSION);if(SSL_CTX_use_certificate_file(c,"/var/lib/pi-guardian/tls/server.crt",SSL_FILETYPE_PEM)<=0||SSL_CTX_use_PrivateKey_file(c,"/var/lib/pi-guardian/tls/server.key",SSL_FILETYPE_PEM)<=0||!SSL_CTX_check_private_key(c)){SSL_CTX_free(c);return NULL;}return c;}
void guardian_run(const guardian_config*cfg){G=*cfg;if(push_init()<0)fprintf(stderr,"warning: VAPID initialization failed\n");SSL_library_init();SSL_load_error_strings();TLS=make_tls();if(!TLS){fprintf(stderr,"TLS certificate/key unavailable\n");exit(1);}pthread_t th;pthread_create(&th,0,watch,0);int s=socket(AF_INET,SOCK_STREAM,0),one=1;setsockopt(s,SOL_SOCKET,SO_REUSEADDR,&one,sizeof(one));struct sockaddr_in a={0};a.sin_family=AF_INET;a.sin_port=htons(cfg->port);a.sin_addr.s_addr=INADDR_ANY;if(bind(s,(struct sockaddr*)&a,sizeof(a))<0||listen(s,32)<0){perror("bind/listen");exit(1);}for(;;){int fd=accept(s,0,0);if(fd<0)continue;SSL*c=SSL_new(TLS);SSL_set_fd(c,fd);if(SSL_accept(c)>0)handle(c);SSL_shutdown(c);SSL_free(c);close(fd);}}
